# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oWPBwB9Xc8kAQHY9hdxS6RqmHqWf669
"""

summary = pd.DataFrame({

    "Metric":[
        "Dataset Size",
        "Train/Test Split",
        "Learning Rate",
        "Epochs",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Value":[
        len(data),
        "80/20",
        0.01,
        20,
        accuracy,
        precision,
        recall,
        f1
    ]
})

summary

import numpy as np
import pandas as pd

col = [
    "Variance",
    "Skewness",
    "Curtosis",
    "Entropy",
    "Class"
]
data = pd.read_csv("/content/banknote+authentication.zip",header=None,names=col)

print("First 5 samples:")
print(data.head(5))

print("Dimension :\n",data.shape)

print("Number of missing values:\n",data.isnull().sum())

print("Statistics:\n",data.describe())

import matplotlib.pyplot as plt
import seaborn as sns

features = data.columns[:-1]

plt.figure(figsize=(12,8))

for i, feature in enumerate(features):

    plt.subplot(2,2,i+1)

    plt.hist(data[feature], bins=20, edgecolor='black')

    plt.title(feature)

    plt.xlabel(feature)

    plt.ylabel("Frequency")

plt.tight_layout()

plt.show()

plt.figure(figsize=(7,6))

sns.heatmap(
    data.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.xlabel("Features")

plt.ylabel("Features")

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=data,
    x="Variance",
    y="Skewness",
    hue="Class"
)

plt.title("Variance vs Skewness")

plt.xlabel("Variance")

plt.ylabel("Skewness")

plt.grid(True)

plt.show()

plt.figure(figsize=(12,6))

for i, col in enumerate(data.columns[:-1]):
    plt.subplot(2,2,i+1)
    sns.boxplot(y=data[col])

plt.tight_layout()
plt.show()

print("Number of duplicated rows:",data.duplicated().sum())

data = data.drop_duplicates()

x = data.drop("Class",axis=1)
y = data["Class"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

class Perceptron:

    def __init__(self, learning_rate=0.01, epochs=20):

        self.lr = learning_rate
        self.epochs = epochs

        self.weights = None
        self.bias = 0

        self.errors = []
        self.weight_history = []
        self.bias_history = []

    def fit(self, X, y):
        def step(x):
            return np.where(x >= 0, 1, 0)

        n_samples, n_features = X.shape

        self.weights = np.zeros(n_features)
        self.bias = 0

        for epoch in range(self.epochs):

            errors = 0

            for xi, target in zip(X, y):

                linear = np.dot(xi, self.weights) + self.bias

                prediction = step(linear)

                update = self.lr * (target - prediction)

                self.weights += update * xi
                self.bias += update

                if update != 0:
                    errors += 1

            self.errors.append(errors)

            self.weight_history.append(self.weights.copy())
            self.bias_history.append(self.bias)

            print(f"Epoch {epoch+1}")

            print("Errors:", errors)

            print("Weights:", self.weights)

            print("Bias:", self.bias)

            print("-"*40)

    def predict(self, X):
        def step(x):
            return np.where(x >= 0, 1, 0)

        linear = np.dot(X, self.weights) + self.bias

        return step(linear)

model = Perceptron(
    learning_rate=0.01,
    epochs=20
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    range(1, model.epochs+1),
    model.errors,
    marker='o'
)

plt.xlabel("Epoch")
plt.ylabel("Misclassified Samples")

plt.title("Training Error vs Epoch")

plt.grid(True)

plt.show()

weights = np.array(model.weight_history)

plt.figure(figsize=(8,5))

for i in range(weights.shape[1]):
    plt.plot(
        weights[:,i],
        label=f"W{i+1}"
    )

plt.legend()

plt.xlabel("Epoch")

plt.ylabel("Weight")

plt.title("Weight Evolution")

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    model.bias_history,
    marker='o'
)

plt.xlabel("Epoch")

plt.ylabel("Bias")

plt.title("Bias Evolution")

plt.grid(True)

plt.show()

learning_rates = [0.001, 0.01, 0.1]

plt.figure(figsize=(8,5))

for lr in learning_rates:

    temp = Perceptron(
        learning_rate=lr,
        epochs=20
    )

    temp.fit(X_train, y_train)

    plt.plot(
        temp.errors,
        label=f"LR={lr}"
    )

plt.legend()

plt.xlabel("Epoch")

plt.ylabel("Errors")

plt.title("Learning Rate Comparison")

plt.grid(True)

plt.show()

history = pd.DataFrame({

    "Epoch": np.arange(1, model.epochs+1),

    "Errors": model.errors,

    "Weight1": [w[0] for w in model.weight_history],

    "Weight2": [w[1] for w in model.weight_history],

    "Bias": model.bias_history

})

history

